// Video-player design concept for my_imgui_sdl3_vulkan.
//
// A standalone program that prototypes the sketched player layout so the interaction
// can be judged before any of it is grafted onto the real player:
//
//   * menu bar across the top
//   * scene view down the left — a thumbnail every N seconds, click to jump
//   * folder view down the right — the clips next to this one, hover to preview
//   * hover preview floating over the video
//   * transport across the bottom — full-width seek strip above the controls
//
// Everything auto-hides, everything slides rather than cuts, and every panel can be
// popped out of the player into its OWN OS window (View > <panel> > options, or the
// [>] button in the panel header).
//
// There is NO decoder here. Frames are generated by FramePattern, which is the point:
// the questions this program answers are about reveal timing, motion, and layout, none
// of which need mpv. Every widget is written against plain data (a timestamp, a tile)
// so the port to real frames touches the draw call and nothing else.
//
// Built as part of the project; run it with:
//   ./build/debug/concept_player   (or: cmake --build build/all --target concept_player)
#include <SDL3/SDL.h>

#include "imgui.h"
#include "imgui_impl_sdl3.h"
#include "imgui_impl_sdlgpu3.h"

#include "concept_player_app.hpp"
#include "motion.hpp"

/// Dark, low-chroma theme: the chrome must never compete with the picture, which is
/// the whole reason the panels are translucent and the only saturated colour in the
/// UI is the played portion of the seek bar.
static void concept_apply_theme()
{
    ImGuiStyle &style = ImGui::GetStyle();
    ImGui::StyleColorsDark();

    style.WindowRounding    = 10.0f;
    style.ChildRounding     = 8.0f;
    style.FrameRounding     = 6.0f;
    style.GrabRounding      = 6.0f;
    style.PopupRounding     = 8.0f;
    style.ScrollbarRounding = 8.0f;
    style.WindowBorderSize  = 0.0f;
    style.FrameBorderSize   = 0.0f;
    style.WindowPadding     = {12.0f, 10.0f};
    style.FramePadding      = {8.0f, 5.0f};
    style.ItemSpacing       = {8.0f, 7.0f};
    style.ScrollbarSize     = 10.0f;

    ImVec4 *c                       = style.Colors;
    c[ImGuiCol_WindowBg]            = {0.07f, 0.075f, 0.09f, 0.94f};
    c[ImGuiCol_ChildBg]             = {0.00f, 0.00f, 0.00f, 0.00f};
    c[ImGuiCol_PopupBg]             = {0.09f, 0.095f, 0.11f, 0.98f};
    c[ImGuiCol_MenuBarBg]           = {0.06f, 0.065f, 0.08f, 1.00f};
    c[ImGuiCol_FrameBg]             = {0.16f, 0.17f, 0.20f, 0.85f};
    c[ImGuiCol_FrameBgHovered]      = {0.22f, 0.24f, 0.28f, 0.95f};
    c[ImGuiCol_FrameBgActive]       = {0.26f, 0.29f, 0.34f, 1.00f};
    c[ImGuiCol_Button]              = {0.18f, 0.19f, 0.23f, 0.90f};
    c[ImGuiCol_ButtonHovered]       = {0.26f, 0.30f, 0.38f, 1.00f};
    c[ImGuiCol_ButtonActive]        = {0.33f, 0.40f, 0.52f, 1.00f};
    c[ImGuiCol_Header]              = {0.22f, 0.26f, 0.34f, 0.85f};
    c[ImGuiCol_HeaderHovered]       = {0.28f, 0.34f, 0.44f, 0.95f};
    c[ImGuiCol_HeaderActive]        = {0.32f, 0.40f, 0.52f, 1.00f};
    c[ImGuiCol_SliderGrab]          = {0.62f, 0.68f, 0.80f, 1.00f};
    c[ImGuiCol_SliderGrabActive]    = {0.82f, 0.86f, 0.95f, 1.00f};
    c[ImGuiCol_Separator]           = {1.00f, 1.00f, 1.00f, 0.10f};
    c[ImGuiCol_Text]                = {0.90f, 0.92f, 0.96f, 1.00f};
    c[ImGuiCol_TextDisabled]        = {0.52f, 0.56f, 0.64f, 1.00f};
    c[ImGuiCol_ScrollbarBg]         = {0.00f, 0.00f, 0.00f, 0.00f};
    c[ImGuiCol_ScrollbarGrab]       = {1.00f, 1.00f, 1.00f, 0.16f};
    c[ImGuiCol_ScrollbarGrabHovered]= {1.00f, 1.00f, 1.00f, 0.28f};
}

/// Applies the startup flags:
///   --popout=scene,folder,controls   start those panels in their own OS windows
///   --pin                            start with every panel held open
/// Unknown arguments are reported and ignored rather than being fatal — this is a
/// design concept, and refusing to launch over a typo helps nobody.
static void concept_apply_args(int argc, char **argv, ConceptPlayerApp &app)
{
    for (int i = 1; i < argc; ++i) {
        const std::string_view arg{argv[i]};
        if (arg == "--pin") {
            app.pin_all(true);
        } else if (arg.starts_with("--popout=")) {
            std::string_view list = arg.substr(std::string_view("--popout=").size());
            while (!list.empty()) {
                const std::size_t comma = list.find(',');
                const std::string_view name = list.substr(0, comma);
                if (!name.empty() && !app.pop_out_panel(name))
                    SDL_Log("concept_player: unknown panel '%.*s' (want scene|folder|controls)",
                            static_cast<int>(name.size()), name.data());
                if (comma == std::string_view::npos)
                    break;
                list.remove_prefix(comma + 1);
            }
        } else {
            SDL_Log("concept_player: ignoring unknown argument '%.*s'",
                    static_cast<int>(arg.size()), arg.data());
        }
    }
}

int main(int argc, char **argv)
{
    if (!SDL_Init(SDL_INIT_VIDEO)) {
        SDL_Log("SDL_Init: %s", SDL_GetError());
        return 1;
    }

    const float      main_scale = SDL_GetDisplayContentScale(SDL_GetPrimaryDisplay());
    SDL_Window *const window =
        SDL_CreateWindow("Video player — design concept",
                         static_cast<int>(1360 * main_scale), static_cast<int>(820 * main_scale),
                         SDL_WINDOW_RESIZABLE | SDL_WINDOW_HIGH_PIXEL_DENSITY);
    if (window == nullptr) {
        SDL_Log("SDL_CreateWindow: %s", SDL_GetError());
        return 1;
    }
    SDL_SetWindowPosition(window, SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED);

    // SDL_GPU rather than SDL_Renderer: the ImGui SDL_Renderer3 backend lists
    // multi-viewport as unsupported, and popping a panel into a real OS window needs
    // it. SDL_GPU is part of SDL3, so this costs no extra dependency.
    SDL_GPUDevice *const gpu = SDL_CreateGPUDevice(
        SDL_GPU_SHADERFORMAT_SPIRV | SDL_GPU_SHADERFORMAT_DXIL | SDL_GPU_SHADERFORMAT_MSL |
            SDL_GPU_SHADERFORMAT_METALLIB,
        false, nullptr);
    if (gpu == nullptr) {
        SDL_Log("SDL_CreateGPUDevice: %s", SDL_GetError());
        return 1;
    }
    if (!SDL_ClaimWindowForGPUDevice(gpu, window)) {
        SDL_Log("SDL_ClaimWindowForGPUDevice: %s", SDL_GetError());
        return 1;
    }
    SDL_SetGPUSwapchainParameters(gpu, window, SDL_GPU_SWAPCHAINCOMPOSITION_SDR,
                                  SDL_GPU_PRESENTMODE_VSYNC);

    IMGUI_CHECKVERSION();
    ImGui::CreateContext();
    ImGuiIO &io = ImGui::GetIO();
    io.IniFilename = nullptr; // don't litter an imgui.ini next to the concept
    io.ConfigFlags |= ImGuiConfigFlags_NavEnableKeyboard;
    io.ConfigFlags |= ImGuiConfigFlags_DockingEnable;

    // ── Viewports: X11 yes, Wayland no ───────────────────────────────────────
    // Multi-viewport is what lets a panel become a real OS window, and it works on
    // X11. On Wayland it does not hold up: the compositor owns window placement and
    // there is no protocol for a client to learn where its window went, so ImGui reads
    // a torn-off panel back as overlapping the host and auto-merge reclaims it. Measured
    // here, the platform-window count collapsed 4 -> 3 -> 2 -> 1 within a second of
    // launch — every popped-out panel silently snapped back.
    //
    // Rather than ship a feature that quietly undoes itself, viewports are simply off
    // under Wayland. Pop-out still works there, as a free-floating window inside the
    // player — movable and resizable, just not its own OS window.
    const char *video_driver = SDL_GetCurrentVideoDriver();
    const bool  is_wayland = video_driver != nullptr && SDL_strncmp(video_driver, "wayland", 7) == 0;
    if (!is_wayland)
        io.ConfigFlags |= ImGuiConfigFlags_ViewportsEnable;

    concept_apply_theme();
    ImGui::GetStyle().ScaleAllSizes(main_scale);
    ImGui::GetStyle().FontScaleDpi = main_scale;
    io.ConfigDpiScaleFonts         = true;
    io.ConfigDpiScaleViewports     = true;

    // Popped-out panels are separate OS windows; leaving WindowBg translucent there
    // would show the desktop through them.
    ImGui::GetStyle().Colors[ImGuiCol_WindowBg].w = 1.0f;

    ImGui_ImplSDL3_InitForSDLGPU(window);
    ImGui_ImplSDLGPU3_InitInfo init_info{};
    init_info.Device               = gpu;
    init_info.ColorTargetFormat    = SDL_GetGPUSwapchainTextureFormat(gpu, window);
    init_info.MSAASamples          = SDL_GPU_SAMPLECOUNT_1;
    init_info.SwapchainComposition = SDL_GPU_SWAPCHAINCOMPOSITION_SDR;
    init_info.PresentMode          = SDL_GPU_PRESENTMODE_VSYNC;
    ImGui_ImplSDLGPU3_Init(&init_info);

    SDL_Log("concept_player: SDL video driver = %s, OS-window pop-out = %s",
            video_driver != nullptr ? video_driver : "?",
            is_wayland ? "off (Wayland — panels pop out in-window instead)" : "on");

    ConceptPlayerApp app;
    concept_apply_args(argc, argv, app);
    bool done                 = false;
    bool window_is_fullscreen = false;
    // Viewports.Size counts the main viewport plus one entry per torn-off panel, so a
    // change here is the ground truth for "an OS window was actually created" —
    // independent of whether the compositor chose to show it where you expected.
    int  last_viewport_count  = -1;

    while (!done) {
        SDL_Event event;
        while (SDL_PollEvent(&event)) {
            ImGui_ImplSDL3_ProcessEvent(&event);
            if (event.type == SDL_EVENT_QUIT)
                done = true;
            if (event.type == SDL_EVENT_WINDOW_CLOSE_REQUESTED &&
                event.window.windowID == SDL_GetWindowID(window))
                done = true;
        }

        if ((SDL_GetWindowFlags(window) & SDL_WINDOW_MINIMIZED) != 0) {
            SDL_Delay(10);
            continue;
        }

        ImGui_ImplSDLGPU3_NewFrame();
        ImGui_ImplSDL3_NewFrame();
        ImGui::NewFrame();
        // ImAnim's mandatory per-frame pump, once, right after NewFrame(). Miss it and
        // every animated value freezes at frame 0 — which reads as "the animation does
        // nothing" rather than as a missing call.
        Motion::begin_frame();

        app.draw();

        if (app.quit_requested())
            done = true;

        // Apply the app's fullscreen intent to the OS window, only on change.
        if (app.fullscreen() != window_is_fullscreen) {
            window_is_fullscreen = app.fullscreen();
            SDL_SetWindowFullscreen(window, window_is_fullscreen);
        }

        ImGui::Render();
        ImDrawData *draw_data   = ImGui::GetDrawData();
        const bool  is_minimized = draw_data->DisplaySize.x <= 0.0f || draw_data->DisplaySize.y <= 0.0f;

        SDL_GPUCommandBuffer *cmd = SDL_AcquireGPUCommandBuffer(gpu);
        SDL_GPUTexture       *swapchain = nullptr;
        SDL_WaitAndAcquireGPUSwapchainTexture(cmd, window, &swapchain, nullptr, nullptr);

        if (swapchain != nullptr && !is_minimized) {
            // Mandatory for this backend: uploads the vertex/index buffers before the
            // render pass that consumes them.
            ImGui_ImplSDLGPU3_PrepareDrawData(draw_data, cmd);

            SDL_GPUColorTargetInfo target{};
            target.texture     = swapchain;
            target.clear_color = SDL_FColor{0.03f, 0.03f, 0.04f, 1.0f};
            target.load_op     = SDL_GPU_LOADOP_CLEAR;
            target.store_op    = SDL_GPU_STOREOP_STORE;

            SDL_GPURenderPass *pass = SDL_BeginGPURenderPass(cmd, &target, 1, nullptr);
            ImGui_ImplSDLGPU3_RenderDrawData(draw_data, cmd, pass);
            SDL_EndGPURenderPass(pass);
        }

        if ((io.ConfigFlags & ImGuiConfigFlags_ViewportsEnable) != 0) {
            ImGui::UpdatePlatformWindows();
            ImGui::RenderPlatformWindowsDefault();

            const int viewport_count = ImGui::GetPlatformIO().Viewports.Size;
            if (viewport_count != last_viewport_count) {
                last_viewport_count = viewport_count;
                SDL_Log("concept_player: platform windows = %d (1 main + %d popped out)",
                        viewport_count, viewport_count - 1);
            }
        }

        SDL_SubmitGPUCommandBuffer(cmd);
    }

    SDL_WaitForGPUIdle(gpu);
    ImGui_ImplSDL3_Shutdown();
    ImGui_ImplSDLGPU3_Shutdown();
    ImGui::DestroyContext();

    SDL_ReleaseWindowFromGPUDevice(gpu, window);
    SDL_DestroyGPUDevice(gpu);
    SDL_DestroyWindow(window);
    SDL_Quit();
    return 0;
}
